---
- name: Converge
  hosts: all
  gather_facts: true

  tasks:
    - name: get setup variables
      debug:
        msg: 
         - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_major_version }}"
         - "{{ ansible_facts.distribution }}"
         - "{{ ansible_facts.os_family }}_{{ ansible_facts.distribution_major_version }}"
         - "{{ ansible_facts.os_family }}"